'use client';

import { useComposerStore } from '@/store/useComposerStore';
import { useEditorStore } from '@/store/useEditorStore';
import DiffView from '@/components/DiffView';
import { X, Sparkles, Send, FileCode, Check, Ban } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useEffect, useRef } from 'react';

export default function Composer() {
  const { isOpen, closeComposer, input, setInput, isGenerating, setIsGenerating, proposedChanges, setProposedChanges } = useComposerStore();
  const { files, updateFileContent } = useEditorStore();
  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'i') {
        e.preventDefault();
        useComposerStore.getState().openComposer();
      }
      if (e.key === 'Escape' && isOpen) closeComposer();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, closeComposer]);

  useEffect(() => {
    if (isOpen && inputRef.current) inputRef.current.focus();
  }, [isOpen]);

  const handleGenerate = async () => {
    if (!(input || '').trim()) return;
    setIsGenerating(true);

    try {
      const response = await fetch('/api/composer', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt: input,
          context: getFullContext(),
        }),
      });

      if (!response.ok) throw new Error('Failed to generate changes');

      // In a real app, we would stream the response and parse it
      // For now, let's pretend we parsed it into proposedChanges
      setProposedChanges([
        { fileId: 'file1', newContent: '// Generated by AI\nconsole.log("Hello from AI Composer");\n' + input }
      ]);
    } catch (error) {
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleAccept = () => {
    if (proposedChanges) {
      proposedChanges.forEach(change => {
        updateFileContent(change.fileId, change.newContent);
      });
      setProposedChanges(null);
      closeComposer();
    }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
          <motion.div
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.95, opacity: 0 }}
            className="w-full max-w-2xl bg-[#1e1e1e] border border-[#333] rounded-xl shadow-2xl overflow-hidden"
          >
            <div className="flex items-center justify-between p-3 border-b border-[#333] bg-[#252526]">
              <div className="flex items-center gap-2 text-sm font-medium text-purple-400">
                <Sparkles size={16} />
                Composer
              </div>
              <button onClick={closeComposer} className="text-[#858585] hover:text-white transition-colors">
                <X size={18} />
              </button>
            </div>
            <div className="p-4 flex flex-col gap-4">
              <textarea
                ref={inputRef}
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Ask Composer to generate code..."
                className="w-full bg-[#2d2d2d] border border-[#3c3c3c] rounded-lg p-3 text-sm text-white focus:outline-none focus:ring-1 focus:ring-purple-500 min-h-[120px] resize-none"
              />

              {proposedChanges && proposedChanges.map((change, idx) => (
                <div key={idx} className="flex flex-col gap-2">
                  <div className="text-xs text-[#858585] flex items-center gap-1">
                    <FileCode size={12} />
                    Proposed change for: {files[change.fileId]?.name}
                  </div>
                  <DiffView
                    oldCode={files[change.fileId]?.content || ''}
                    newCode={change.newContent}
                  />
                </div>
              ))}

              <div className="flex items-center justify-between mt-2">
                <div className="flex items-center gap-2 text-[11px] text-[#858585]">
                  <FileCode size={14} />
                  {proposedChanges ? `${proposedChanges.length} files proposed` : 'Context active'}
                </div>

                <div className="flex gap-2">
                  {proposedChanges ? (
                    <>
                      <button
                        onClick={() => setProposedChanges(null)}
                        className="flex items-center gap-2 bg-[#2d2d2d] hover:bg-[#3d3d3d] text-white px-4 py-2 rounded-md text-sm font-medium transition-colors"
                      >
                        <Ban size={14} />
                        Reject
                      </button>
                      <button
                        onClick={handleAccept}
                        className="flex items-center gap-2 bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-md text-sm font-medium transition-colors"
                      >
                        <Check size={14} />
                        Accept
                      </button>
                    </>
                  ) : (
                    <button
                      onClick={handleGenerate}
                      disabled={isGenerating || !(input || '').trim()}
                      className="flex items-center gap-2 bg-purple-600 hover:bg-purple-700 text-white px-4 py-2 rounded-md text-sm font-medium transition-colors"
                    >
                      {isGenerating ? "Generating..." : "Generate"}
                    </button>
                  )}
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
}
